### ISSUE TITLE
Moment Timezone code required.

### ISSUE THREAD

**Issue by shirleyqiantingliu** [OpusCapita/isodata#75]
Hi,
We are using timezones from isodata to create schedules for each timezone to bull. And bull is using Moment for handling timezones.
We often get errors like the following:
Moment Timezone has no data for AEST. See http://momentjs.com/timezone/docs/#/data-loading/.
It is because the ID of timezone is not supported, but Moment supports the format like "Africa/Abidjan".
Is it possible to consider adding Moment timezone code to the timezone model?

**Comment by shirleyqiantingliu** [comment]
@nczeranka @torepettersen

**Comment by nczeranka** [comment]
Please do not create tickets on github because they are not taken into account for planning.
In case of needed improvements, please contact the responsible Stream leads / Product Manager.
